<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by sqlni, ${time} -->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="${namespace}">

<#list resultMaps as resultMap>
  <resultMap id="${resultMap.id}" type="${resultMap.type}">

  </resultMap>

</#list>
<#list methods as method>


</#list>

</mapper>