<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by sqlni, ${time} -->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="${namespace}">

<#list resultMaps as resultMap>
  <resultMap id="${resultMap.id}" type="${resultMap.type}">
<#list resultMap.idList as id>
    <id property="${id.property}" column="${id.column}"<#if id.javaType?has_content> javaType="${id.javaType}"</#if><#if id.jdbcType?has_content> jdbcType="${id.jdbcType}"</#if><#if id.typeHandler?has_content> typeHandler="${id.typeHandler}"</#if>/>
</#list>
<#list resultMap.resultList as id>
    <result property="${id.property}" column="${id.column}"<#if id.javaType?has_content> javaType="${id.javaType}"</#if><#if id.jdbcType?has_content> jdbcType="${id.jdbcType}"</#if><#if id.typeHandler?has_content> typeHandler="${id.typeHandler}"</#if>/>
</#list>
<#list resultMap.associationList as association>
    <association property="${association.property}" column="${association.column}" select="${association.select}"<#if association.fetchType?has_content> fetchType="${association.fetchType}"</#if>/>
</#list>
<#list resultMap.collectionList as collection>
    <collection property="${collection.property}" column="${collection.column}" select="${collection.select}"<#if collection.fetchType?has_content> fetchType="${collection.fetchType}"</#if>/>
</#list>
  </resultMap>

</#list>
<#list methods as method>
<#if method.comment?has_content>
  <!--
<#list method.comment as line>
    ${line}
</#list>
  -->
</#if>
  <select id="${method.id}"<#if method.resultMap?has_content> resultMap="${method.resultMap}"<#else> resultType="${method.resultType}" </#if>>
    select * from ( select row_.*, rownum rownum_ from ( select * from t_table as t where MIF('sadfa'|| 'PARAM_[param]'|| '1312'='sdfsdfdsfds', c1 = [#{param1}], 1=1) and c2 <> 'sadfa'|| 'asdf'|| '1312' ) row_ where rownum <= 9) where rownum_ > 6
  </select>

</#list>

</mapper>